<?php
/**
 * Created by PhpStorm.
 * User: 17715
 * Date: 2018/11/7
 * Time: 23:00
 */

namespace app\index\model;


use think\Hook;
use think\Model;

class Right extends Model
{
    public $rid;
    public $noAccessModul;
    public $level;
    public $groupName;
    public $create_time;
    public $update_time;
    protected $pk="rid";
    protected $table="user_right_group";
    protected $createTime="create_time";
    protected $updateTime="update_time";
    protected $autoWriteTimestamp="datetime";
    public function __construct($data = [])
    {
        parent::__construct($data);
    }
    public function save($data = [], $where = [], $sequence = null)
    {
        //默认不允许进入的模块
        $this->noAccessModul=json_encode(["admin","section"]);
        return parent::save($data, $where, $sequence); // TODO: Change the autogenerated stub
    }
}